# https://galaxy.ansible.com/gantsign/oh-my-zsh
- src: gantsign.oh-my-zsh

# https://github.com/viasite-ansible/ansible-role-zsh
# - src: https://github.com/viasite-ansible/ansible-role-zsh
#   name: viasite-ansible.zsh

# https://galaxy.ansible.com/gantsign/git_user
- src: gantsign.git_user

# https://galaxy.ansible.com/brentwg/visual-studio-code
- src: brentwg.visual-studio-code

# https://galaxy.ansible.com/gantsign/visual-studio-code-extensions
- src: gantsign.visual-studio-code-extensions

# https://galaxy.ansible.com/gantsign/atom
- src: gantsign.atom

# https://galaxy.ansible.com/gantsign/golang
- src: gantsign.golang

# https://galaxy.ansible.com/gantsign/minikube
- src: gantsign.minikube

# https://galaxy.ansible.com/gantsign/helm
- src: gantsign.helm

# https://galaxy.ansible.com/geerlingguy/docker
- src: geerlingguy.docker

# https://galaxy.ansible.com/robertdebock/cntlm
# - src: robertdebock.cntlm

# https://galaxy.ansible.com/gantsign/keyboard
- src: gantsign.keyboard

# https://galaxy.ansible.com/gantsign/postman
- src: gantsign.postman

# https://galaxy.ansible.com/gantsign/timezone
- src: gantsign.timezone

# https://github.com/gantsign/ansible-role-xdesktop
- name: gantsign.xdesktop
  src: https://github.com/gantsign/ansible-role-xdesktop

# https://galaxy.ansible.com/gantsign/pin-to-launcher
- name: gantsign.pin-to-launcher

# https://galaxy.ansible.com/gantsign/terminator
- name: gantsign.terminator

# https://galaxy.ansible.com/oefenweb/chrome
# - name: oefenweb.chrome
- name: mlangry.google-chrome

# https://galaxy.ansible.com/claude_leveille/slack
# - name: claude_leveille.slack
- name: oefenweb.slack

# https://galaxy.ansible.com/geerlingguy/pip
- name: geerlingguy.pip

# https://galaxy.ansible.com/gantsign/intellij
- name: gantsign.intellij

# https://galaxy.ansible.com/oefenweb/pycharm
- name: oefenweb.pycharm

# https://github.com/vkill/ansible-role-gpg_key
- name: gpg_key
  src: https://github.com/vkill/ansible-role-gpg_key

# https://galaxy.ansible.com/gantsign/pipenv
- name: gantsign.pipenv
# https://galaxy.ansible.com/gantsign/pyenv
- name: gantsign.pyenv

# https://galaxy.ansible.com/geerlingguy/ansible-role-packer
- name: geerlingguy.packer

# https://galaxy.ansible.com/chaosmail/sublime-text
- name: chaosmail.sublime-text

# https://galaxy.ansible.com/gantsign/java
# - name: gantsign.java

# https://galaxy.ansible.com/gantsign/maven
# - name: gantsign.maven

# https://galaxy.ansible.com/geerlingguy/nodejs/
# - name: geerlingguy.nodejs

# https://galaxy.ansible.com/gantsign/sdkman
- name: gantsign.sdkman
# https://galaxy.ansible.com/gantsign/sdkman_init
- name: gantsign.sdkman_init

# https://galaxy.ansible.com/cimon-io/asdf
- name: cimon-io.asdf

######################################################
# MEMO
######################################################

# # Install a role from the Ansible Galaxy
# - src: dfarrell07.opendaylight

# # Install a role from GitHub
# - name: opendaylight
#   src: https://github.com/dfarrell07/ansible-opendaylight

# # Install a role from a specific git branch
# - name: opendaylight
#   src: https://github.com/dfarrell07/ansible-opendaylight
#   version: origin/master

# # Install a role at a specific tag from GitHub
# - name: opendaylight
#   src: https://github.com/dfarrell07/ansible-opendaylight
#   version: 1.0.0

# # Install a role at a specific commit from GitHub
# - name: opendaylight
#   src: https://github.com/dfarrell07/ansible-opendaylight
#   version: <commit hash>