---

- name: Download tfenv
  get_url:
    url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
    dest: "{{ binary_tmp_directory }}/terraform-{{terraform_version}}.zip"

- git:
    repo: "https://github.com/tfutils/tfenv.git"
    dest: "/home/{{ username }}/.tfenv"